//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int ID { get; set; }
        public string ReadingHref { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public string RadioHref { get; set; }
        public string CoverSrc { get; set; }
        public Nullable<bool> IsBook { get; set; }
    }
}
