//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string username { get; set; }
        public string password { get; set; }
        public int id { get; set; }
        public int role { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
        public byte[] avatar { get; set; }
        public Nullable<int> type { get; set; }
    }
}
